cycM edits to 3durma triggers/jobs

diff --git a/jobs/JOBSPROC_URMA_DUMP_POST b/jobs/JOBSPROC_URMA_DUMP_POST
--- a/jobs/JOBSPROC_URMA_DUMP_POST
+++ b/jobs/JOBSPROC_URMA_DUMP_POST
@@ -66,7 +66,19 @@ set -x
 ###########################
 export obsNET=${obsNET:-obsproc}
 export NET=${NET:-urma}
-export RUN=${RUN:-urma}
+
+echo $job | grep "_ru_"
+err_ru=$?
+if [ $err_ru = 0 ]; then
+  export RUN=${RUN:-urma_ru}  # rapid update w/ sub-hourly cycles
+  set +x
+  echo
+  echo cycM is ${cycM:?"###FATAL ERROR \"cycM\" is not set"}
+  echo
+  set -x
+else
+  export RUN=${RUN:-urma}     # normal, hourly cycle run
+fi
 
 set +x
 echo
@@ -81,6 +93,16 @@ set -x
 ##############################
 export cycle=t${cyc}z
 export tmmark=tm00
+
+# Imported variable cycM, if it exists, contains cycle time minutes
+#  If cycM is imported, reset cycle in this script only (cycle_here) to 4-digit
+#   value t<HHMM>z
+#   (Note: the reset here applies only to references to $cycle, changed now to
+#          $cycle_here, in this script; downstream scripts
+#          exrtma_makeprepbufr.sh.ecf and prepobs_makeprepbufr.sh will later
+#          reset actual $cycle in the same manner)
+cycle_here=$cycle
+[ -n "$cycM" ]  &&  cycle_here=t${cyc}${cycM}z
 
 ###############################
 # Create new working directory
@@ -220,16 +242,16 @@ $SCRIPTSobsproc/exdump_post.sh
 eval err_${RUN}_dump_post=$?
 eval [[ \$err_${RUN}_dump_post -ne 0 ]]  && $DATA/err_exit
 
-echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_dump_post_ran
+echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle_here}_${RUN}_dump_post_ran
 
-> $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
+> $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_dump_post_run
 [ -n "$obsproc_ver" ]  &&  \
  echo "OBSPROC version is $obsproc_ver" >> \
- $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
+ $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_dump_post_run
 
 [ -n "$bufr_dump_ver" ]  &&  \
  echo "BUFR_DUMP version used by this job is $bufr_dump_ver" >> \
- $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
+ $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_dump_post_run
 
 if [ "$KEEPDATA" != YES ]; then
    cd $DATAROOT
diff --git a/jobs/JOBSPROC_URMA_PREP b/jobs/JOBSPROC_URMA_PREP
--- a/jobs/JOBSPROC_URMA_PREP
+++ b/jobs/JOBSPROC_URMA_PREP
@@ -59,7 +59,19 @@ set -x
 ###########################
 export obsNET=${obsNET:-obsproc}
 export NET=${NET:-urma}
-export RUN=${RUN:-urma}
+
+echo $job | grep "_ru_"
+err_ru=$?
+if [ $err_ru = 0 ]; then
+  export RUN=${RUN:-urma_ru}  # rapid update w/ sub-hourly cycles
+  set +x
+  echo
+  echo cycM is ${cycM:?"###FATAL ERROR \"cycM\" is not set"}
+  echo
+  set -x
+else
+  export RUN=${RUN:-urma}     # normal, hourly cycle run
+fi
 
 set +x
 echo
@@ -74,6 +86,16 @@ set -x
 ##############################
 export cycle=t${cyc}z
 export tmmark=tm00
+
+# Imported variable cycM, if it exists, contains cycle time minutes
+#  If cycM is imported, reset cycle in this script only (cycle_here) to 4-digit
+#   value t<HHMM>z
+#   (Note: the reset here applies only to references to $cycle, changed now to
+#          $cycle_here, in this script; downstream scripts
+#          exrtma_makeprepbufr.sh.ecf and prepobs_makeprepbufr.sh will later
+#          reset actual $cycle in the same manner)
+cycle_here=$cycle
+[ -n "$cycM" ]  &&  cycle_here=t${cyc}${cycM}z
 
 ###############################
 # Create new working directory
@@ -273,12 +295,12 @@ $SCRIPTSobsproc/exurma_makeprepbufr.sh
 eval err_${RUN}_makeprepbufr=$?
 eval [[ \$err_${RUN}_makeprepbufr -ne 0 ]] && $DATA/err_exit
 
-echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_prep_ran
+echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle_here}_${RUN}_prep_ran
 
-> $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_run
+> $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_prep_run
 [ -n "$obsproc_ver" ]  &&  \
  echo "OBSPROC version is $obsproc_ver" >> \
- $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_run
+ $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_prep_run
 
 # Adding time lag to the end of the job to allow PREPBUFR to be copied
 #  completely before the start of the next job in the trigger's sequence
