Final changes

diff --git a/jobs/JOBSPROC_RAP_DUMP_POST b/jobs/JOBSPROC_RAP_DUMP_POST
--- a/jobs/JOBSPROC_RAP_DUMP_POST
+++ b/jobs/JOBSPROC_RAP_DUMP_POST
@@ -35,22 +35,24 @@ set +x
 echo
 echo "####################################################################"
 echo
-echo "Current OBSPROC version is ${obsproc_ver:-not set}"
+echo "OBSPROC version is ${obsproc_ver:-not set}"
+echo "BUFR_DUMP version used by this job, for dumplist, is" \
+       "${bufr_dump_ver:-not set}"
+if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)bufr_dump/") -eq 0 ]];
+	then echo "bufr_dump is required but not loaded! Exiting...";
+	exit;
+fi
+
 echo
 echo "####################################################################"
 echo
 set -x
 
 #####################################################################
-## List modules loaded for this job
-##   On luna/surge may need to initialize the Modules package to find
-##   the module command.  Will do so for either system.
-######################################################################
-#if [ -f /opt/modules/default/init/sh ]; then  # on luna/surge
-#  . /opt/modules/default/init/sh 2>/dev/null
-#elif [ -f /usrx/local/Modules/default/init/sh ]; then  # on tide/gyre
-#  . /usrx/local/Modules/default/init/sh 2>/dev/null
-#fi
+# List modules loaded for this job
+#   On luna/surge may need to initialize the Modules package to find
+#   the module command.  Will do so for either system.
+#####################################################################
 set +x
 echo
 echo "####################################################################"
@@ -61,9 +63,10 @@ echo "####################################################################"
 echo
 set -x
 
-######################
-# Specify NET and RUN
-######################
+###########################
+# Specify NET and RUN Name
+###########################
+export obsNET=${obsNET:-obsproc}
 export NET=${NET:-rap}
 echo $job | grep pcyc
 err_p=$?
@@ -76,6 +79,14 @@ elif [ $err_e = 0 ]; then
 else
   export RUN=${RUN:-rap}    # Full cycle
 fi
+set +x
+echo
+echo obsNET is ${obsNET:?"###FATAL ERROR \"obsNET\" is not set"}
+echo NET is ${NET:?"###FATAL ERROR \"NET\" is not set"}
+echo RUN is ${RUN:?"###FATAL ERROR \"RUN\" is not set"}
+echo
+set -x
+
 
 ##############################
 # Specify cycle and time-mark
@@ -86,23 +97,31 @@ export tmmark=tm00
 ###############################
 # Create new working directory
 ###############################
-jobid=${jobid:-${job}.$(hostname -s).$$}
-export DATA=${DATA:-$DATAROOT/${jobid}}
+host=$(hostname -s)
+export DATA=${DATA:-$DATAROOT/${jobid}.${host}}
 rm -rf $DATA
 mkdir -p $DATA
 cd $DATA
-export pgmout=OUTPUT.$$
 
 ######################################
 # Set job log file for postmsg output
 ######################################
 jlogfile=${jlogfile:-${DATA}/jlogfile}
 
-#################################################
-# SENDCOM      - Copy files to $COMOUT directory
-# SENDECF      - Flag Events on ECFLOW
-# SENDDBN      - Alert output file to TOC
-#################################################
+######################################
+# Determine Job Output Name on System
+######################################
+export pid=$$
+export outid="LL$job"
+[ $envir != prod ]  && export outid="LL${job}_${envir}"
+export jobid="${outid}.o${pid}"
+export pgmout="OUTPUT.${pid}"
+
+############################################
+# SENDCOM  - Copy files to $COMOUT directory
+# SENDECF  - Flag Events on ECFLOW
+# SENDDBN  - Alert output file to TOC
+############################################
 export SENDCOM=${SENDCOM:-YES}
 export SENDECF=${SENDECF:-YES}
 export SENDDBN=${SENDDBN:-YES}
@@ -112,16 +131,24 @@ export SENDDBN=${SENDDBN:-YES}
 ##########################
 
 # -------------------------------
-# Paths for obsproc items
+# Paths for obsproc_network items
 # -------------------------------
 export HOMEobsproc=${HOMEobsproc:\
--${PACKAGEROOT:?}/obsproc_rap.${obsproc_ver:?\
+-${PACKAGEROOT:?}/obsproc.${obsproc_ver:?\
 "###FATAL ERROR \"obsproc_ver\" is not set"}}
 
 export SCRIPTSobsproc=${SCRIPTSobsproc:-$HOMEobsproc/scripts}
 export EXECobsproc=${EXECobsproc:-$HOMEobsproc/exec}
 export USHobsproc=${USHobsproc:-$HOMEobsproc/ush}
-export FIXobsproc=${FIXobsproc:-$HOMEobsproc/fix}
+
+# --------------------------------------------
+# Paths for bufr_dumplist items
+# --------------------------------------------
+export HOMEbufr_dump=${HOMEbufr_dump:\
+-${PACKAGEROOT:?}/bufr_dump.${bufr_dump_ver:?\
+"###FATAL ERROR \"bufr_dump_ver\" is not set"}}
+
+export FIXbufr_dump=${FIXbufr_dump:-$HOMEbufr_dump/fix}
 
 #########################################################################
 # Add some prod utilities to working directory
@@ -145,49 +172,89 @@ cp $UTILROOT/ush/setpdy.sh .; chmod +x setpdy.sh
 export COMIN_ROOT=${COMIN_ROOT:-${COMROOT:-""}}
 
 if [[ "$RUN_ENVIR" == nco ]]; then
-	export COMIN=${COMIN_ROOT:?}/obsproc/${obsproc_ver}/${RUN}.${PDY}
-  export COMOUT=${COMROOT:?}/obsproc/${obsproc_ver}/${RUN}.${PDY}
+  export COMIN=${COMIN:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
+  export COMOUT=${COMOUT:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
   mkdir -m 775 -p $COMOUT
 else
-  export COMIN=${COMIN:-${COMIN_ROOT:?}/obsproc/${obsproc_ver}/${RUN}.${PDY}}
+  export COMIN=${COMIN:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
 
 # COMOUT_ROOT for developers defaults to unique $DATA/com directory as root to
 #  prevent job from writing into a non-unique directory that might already have
 #  output in it from a previous checkout run for the same cycle
 # -----------------------------------------------------------------------------
   export COMOUT_ROOT=${COMOUT_ROOT:-${DATA}/com}
-  export COMOUT=${COMOUT:-${COMOUT_ROOT}/obsproc/${obsproc_ver}/${RUN}.${PDY}}
+  export COMOUT=${COMOUT:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
   mkdir -m 755 -p $COMOUT
 fi
 
-################################################################################
-# SETUP RAP (full cyc) or RAP_P (partial cyc) POST-ANAL PREPBUFR PROC. VARIABLES
-# SETUP RAP_E (early) POST-PREPBUFR PROCESSING VARIABLES
-################################################################################
+# comin and comin_m1 are paths to dump status files for bufr_avgdata.sh
+export comin=${comin:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
+export comin_m1=${comin_m1:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
+
+# ---------------------------
+# Paths for non-obsproc items
+# ---------------------------
+
+# directory path to data count averaging executed in model script and in
+#  bufr_avgdata.sh
+# ----------------------------------------------------------------------
+export HOMEARCH=${HOMEarch:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/sdm_rtdm/$RUN)}
+  
+#  .. AVGDarch_OUT is directory path for avg tables output by model script
+#     --------------------------------------------------------------------
+if [[ "$RUN_ENVIR" == nco ]]; then
+  export AVGDarch_OUT=$HOMEarch/avgdata
+  mkdir -p $AVGDarch_OUT
+else
+  export AVGDarch_OUT=${AVGDarch_OUT:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/sdm_rtdm/${RUN}/avgdata)}
+  mkdir -p $AVGDarch_OUT
+fi
+
+# .. OBCNTarch is directory path to write new status files to & read all status
+#    files from {can WRITE to this location only if COPY=YES (the default)
+#    --------------------------------------------------------------------------
+export OBCNTarch=${OBCNTarch:-$HOMEarch/obcount_30day}
+
+#############################################################################
+# SETUP RAP (full cycle), RAP_P (partial cycle) or RAP_E (early cycle) DATA
+#  DUMP POST PROCESSING VARIABLES
+#############################################################################
 
 #########################################################
 # Specify variables specific to this execution of script
 #########################################################
+export PROCESS_DATACOUNTS=NO # Not processed in RAP, RAP_P, RAP_E runs
 export PROCESS_REMOREST=${PROCESS_REMOREST:-YES}
-export PROCESS_TIMETWINS=NO  # can never run here
-export PROCESS_ALL_REPORT_COUNTS=NO  # can never run here
+export PROCESS_UNBLKBUFR=${PROCESS_UNBLKBUFR:-NO}
+export PROCESS_LISTERS=${PROCESS_LISTERS:-YES}
+
+# Data count average tables are generated in the 23Z (full cycle) run only
+if [ "$RUN" = 'rap' -a "$cyc" = '23' ]; then
+   export PROCESS_AVGTABLES=${PROCESS_AVGTABLES:-YES}
+else
+   export PROCESS_AVGTABLES=${PROCESS_AVGTABLES:-NO}
+fi
 
 env
 
 #####################
 # Execute the script
 #####################
-$SCRIPTSobsproc/exprep_post.sh
-err_prep_post=$?
-eval err_${RUN}_prep_post=${err_prep_post}
-[[ $err_prep_post -ne 0 ]] && $DATA/err_exit
+$SCRIPTSobsproc/exdump_post.sh
+err_dump_post=$?
+eval err_${RUN}_dump_post=${err_dump_post}
+[[ $err_dump_post -ne 0 ]] && $DATA/err_exit
 
-echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_prep_post_ran
+echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_dump_post_ran
 
-> $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_post_run
-[ -n "$obsproc_ver" ]  &&  \
+> $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
+[ -n "$obsproc_rap_ver" ]  &&  \
  echo "OBSPROC version is $obsproc_ver" >> \
- $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_post_run
+ $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
+
+[ -n "$bufr_dump_ver" ]  &&  \
+ echo "BUFR_DUMP version used by this job is $bufr_dump_ver" >> \
+ $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
 
 if [ "$KEEPDATA" != YES ]; then
    cd $DATAROOT
