Updated URMA script post-Cactus swap

diff --git a/jobs/JOBSPROC_URMA_DUMP b/jobs/JOBSPROC_URMA_DUMP
--- a/jobs/JOBSPROC_URMA_DUMP
+++ b/jobs/JOBSPROC_URMA_DUMP
@@ -37,7 +37,7 @@ echo "####################################################################"
 echo
 echo "OBSPROC version is ${obsproc_ver:-not set}"
 echo "BUFR_DUMP version used by this job, for dump and dumplist, is" \
-       "${bufr_dump_ver:-not set}"
+     "${bufr_dump_ver:-not set}"
 echo "grib_util module version used by this job is ${grib_util_ver:-not set}"
 if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)bufr_dump/") -eq 0 ]];
      then echo "bufr_dump is required but not loaded! Exiting...";
@@ -48,9 +48,9 @@ echo "####################################################################"
 echo
 set -x
 
-######################################################
-# List modules needed by this job
-######################################################
+#######################################################
+# List modules loaded for this job
+#######################################################
 set +x
 echo
 echo "####################################################################"
@@ -61,26 +61,49 @@ echo "####################################################################"
 echo
 set -x
 
-###########################
-# Specify NET and RUN Name
-###########################
+######################
+# Specify NET and RUN
+######################
 export obsNET=${obsNET:-obsproc}
 export NET=${NET:-urma}
-export RUN=${RUN:-urma}
+#export RUN=${RUN:-urma}
 
 set +x
 echo
 echo obsNET is ${obsNET:?"###FATAL ERROR \"obsNET\" is not set"}
 echo NET is ${NET:?"###FATAL ERROR \"NET\" is not set"}
-echo RUN is ${RUN:?"###FATAL ERROR \"RUN\" is not set"}
+#echo RUN is ${RUN:?"###FATAL ERROR \"RUN\" is not set"}
 echo
 set -x
+
+echo $job | grep "_ru_"
+err_ru=$?
+if [ $err_ru = 0 ]; then
+  export RUN=${RUN:-urma_ru}  # rapid update w/ sub-hourly cycles
+  set +x
+  echo
+  echo cycM is ${cycM:?"###FATAL ERROR \"cycM\" is not set"}
+  echo
+  set -x
+else
+  export RUN=${RUN:-urma}     # normal, hourly cycle run
+fi
 
 ##############################
 # Specify cycle and time-mark
 ##############################
 export cycle=t${cyc}z
 export tmmark=tm00
+
+# Imported variable cycM, if it exists, contains cycle time minutes
+#  If cycM is imported, reset cycle in this script only (cycle_here) to 4-digit
+#   value t<HHMM>z
+#   (Note: the reset here applies only to references to $cycle, changed now to
+#          $cycle_here, in this script; downstream script exurma_dump.sh.ecf
+#          will later reset actual $cycle in the same manner)
+
+cycle_here=$cycle
+[ -n "$cycM" ]  &&  cycle_here=t${cyc}${cycM}z
 
 ###############################
 # Create new working directory
@@ -117,22 +140,14 @@ export SENDDBN=${SENDDBN:-YES}
 ##########################
 
 # -------------------------------
-# Paths for obsproc_network items
+# Paths for obsproc items
 # -------------------------------
 export HOMEobsproc=${HOMEobsproc:\
--${PACKAGEROOT:?}/obsproc/${obsproc_ver:?\
+-${PACKAGEROOT:?}/${obsNET}/${obsproc_ver:?\
 "###FATAL ERROR \"obsproc_ver\" is not set"}}
 
 export SCRIPTSobsproc=${SCRIPTSobsproc:\
 -$HOMEobsproc/scripts}
-
-# -----------------------------------------------------
-# Paths for dump and bufr_dumplist items
-# Variables pre-defined when bufr_dump module is loaded
-# -----------------------------------------------------
-
-export USHbufr_dump=${USHbufr_dump:-$HOMEbufr_dump/ush}
-export FIXbufr_dump=${FIXbufr_dump:-$HOMEbufr_dump/fix}
 
 # NOTE: path to dump executables defaults to $HOMEbufr_dump/exec in dumpjb
 
@@ -169,9 +184,9 @@ export FIXbufr=${FIXbufr:-$HOMEbufr_dump/fix}
 # Paths for non-obsproc items
 # ---------------------------
 
+# TANK is root directory path to observational database used in dumpjb
 # --------------------------------------------------------------------
 export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/${envir}/dcom}
-echo $DCOMROOT
 export TANK=${TANK:-${DCOMROOT}}
 
 #########################################################################
@@ -203,7 +218,6 @@ if [[ "$RUN_ENVIR" == nco ]]; then
 else
   export COMIN=${COMIN:-${COMIN_ROOT:?}/${obsNET}/${obsproc_ver}/${RUN}.${PDY}}
 
-
 # COMOUT_ROOT for developers defaults to unique $DATA/com directory as root to
 #  prevent job from writing into a non-unique directory that might already have 
 #  output in it from a previous checkout run for the same cycle
@@ -214,7 +228,7 @@ else
 fi
 
 ############################################
-# SETUP URMA DATA DUMP PROCESSING VARIABLES
+# SETUP RMTA DATA DUMP PROCESSING VARIABLES
 ############################################
 
 #########################################################
@@ -237,6 +251,7 @@ export PREPSSMI_PROD_TYPE=NEURAL_NET3
 #   nam_expdomain_guam_halfdeg_imask.gbl
 export LALO=${LALO:-"F$FIXPREP/nam_expdomain_guam_halfdeg_imask.gbl"}
 
+
 export BACK=off # background threads not allowed
 
 env
@@ -248,17 +263,17 @@ $SCRIPTSobsproc/exurma_dump.sh
 eval err_${RUN}_dump=$?
 eval [[ \$err_${RUN}_dump -ne 0 ]] && $DATA/err_exit
 
-echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_dump_ran
+echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle_here}_${RUN}_dump_ran
 
-> $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_run
-[ -n "$obsproc_urma_ver" ]  &&  \
+> $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_dump_run
+[ -n "$obsproc_ver" ]  &&  \
  echo "OBSPROC version is $obsproc_ver" >> \
- $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_run
+ $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_dump_run
 [ -n "$bufr_dump_ver" ]  &&  \
  echo "BUFR_DUMP version used by this job is $bufr_dump_ver" >> \
- $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_run
+ $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_dump_run
 echo "Version of module \"grib_util\" used by this job is $grib_util_ver" \
- >> $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_run
+ >> $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_dump_run
 
 if [ "$KEEPDATA" != YES ]; then
    cd $DATAROOT
diff --git a/jobs/JOBSPROC_URMA_DUMP_POST b/jobs/JOBSPROC_URMA_DUMP_POST
--- a/jobs/JOBSPROC_URMA_DUMP_POST
+++ b/jobs/JOBSPROC_URMA_DUMP_POST
@@ -36,8 +36,8 @@ echo
 echo "####################################################################"
 echo
 echo "OBSPROC version is ${obsproc_ver:-not set}"
-echo "BUFR_DUMP version used by this job, for dumplist, is " \
-       "${bufr_dump_ver:-not set}"
+echo "BUFR_DUMP version used by this job, for dump and dumplist, is" \
+     "${bufr_dump_ver:-not set}"
 echo "grib_util module version used by this job is ${grib_util_ver:-not set}"
 if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)bufr_dump/") -eq 0 ]];
      then echo "bufr_dump is required but not loaded! Exiting...";
@@ -49,8 +49,8 @@ echo
 set -x
 
 #####################################################################
-### List modules loaded for this job.
-#######################################################################
+## List modules loaded for this job.
+######################################################################
 set +x
 echo
 echo "####################################################################"
@@ -66,15 +66,29 @@ set -x
 ###########################
 export obsNET=${obsNET:-obsproc}
 export NET=${NET:-urma}
-export RUN=${RUN:-urma}
 
 set +x
 echo
 echo obsNET is ${obsNET:?"###FATAL ERROR \"obsNET\" is not set"}
 echo NET is ${NET:?"###FATAL ERROR \"NET\" is not set"}
-echo RUN is ${RUN:?"###FATAL ERROR \"RUN\" is not set"}
 echo
 set -x
+
+echo $job | grep "_ru_"
+err_ru=$?
+if [ $err_ru = 0 ]; then
+  export RUN=${RUN:-urma_ru}  # rapid update w/ sub-hourly cycles
+  set +x
+  echo
+  echo cycM is ${cycM:?"###FATAL ERROR \"cycM\" is not set"}
+  echo
+  set -x
+else
+  export RUN=${RUN:-urma}     # normal, hourly cycle run
+fi
+
+echo RUN is ${RUN:?"###FATAL ERROR \"RUN\" is not set"}
+
 
 ##############################
 # Specify cycle and time-mark
@@ -110,20 +124,20 @@ export SENDDBN=${SENDDBN:-YES}
 # Specify Execution Areas
 ##########################
 
-# -------------------------------
+# ------------------------
 # Paths for obsproc items
-# -------------------------------
+# ------------------------
 export HOMEobsproc=${HOMEobsproc:\
--${PACKAGEROOT:?}/obsproc/${obsproc_ver:?\
-"###FATAL ERROR \"obsproc_urma_ver\" is not set"}}
+-${PACKAGEROOT:?}/${obsNET}/${obsproc_ver:?\
+"###FATAL ERROR \"obsproc_ver\" is not set"}}
 
 export SCRIPTSobsproc=${SCRIPTSobsproc:-$HOMEobsproc/scripts}
 export EXECobsproc=${EXECobsproc:-$HOMEobsproc/exec}
 export USHobsproc=${USHobsproc:-$HOMEobsproc/ush}
 
 #########################################################################
-### Add some prod utilities to working directory
-###########################################################################
+## Add some prod utilities to working directory
+##########################################################################
 echo "step ############# break ##############################" > ./break
 cp $UTILROOT/ush/err_chk   .; chmod +x err_chk
 cp $UTILROOT/ush/err_exit  .; chmod +x err_exit
@@ -138,6 +152,13 @@ set +x; echo -e "\n---> path to setpdy.sh below is: `which setpdy.sh`"; set -x
 setpdy.sh
 . $DATA/PDY
 
+# Imported variable cycM, if it exists, contains cycle time minutes
+#  If cycM is imported, reset exported cycle to 4-digit value t<HHMM>z
+#  (Note: This value for $cycle will now be used in this script and in
+#         downstream script exdump_post.sh.ecf)
+
+[ -n "$cycM" ]  &&  cycle=t${cyc}${cycM}z
+
 #########################
 # Define COM directories
 #########################
@@ -145,8 +166,7 @@ export COMIN_ROOT=${COMIN_ROOT:-${COMROOT:-""}}
 
 if [[ "$RUN_ENVIR" == nco ]]; then
   export COMIN=${COMIN:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
-  #export COMOUT=${COMOUT:-$(compath.py -o ${obsNET}/$obsproc_ver/${RUN}.${PDY})}
-  export COMOUT=${COMOUT:-$(compath.py -o  ${obsNET}/$obsproc_ver/${RUN}.${PDY})}
+  export COMOUT=${COMOUT:-$(compath.py -o ${obsNET}/$obsproc_ver/${RUN}.${PDY})}
   mkdir -m 775 -p $COMOUT
 else
   export COMIN=${COMIN:-${COMIN_ROOT:?}/${obsNET}/${obsproc_ver}/${RUN}.${PDY}}
@@ -171,16 +191,14 @@ export comin_m1=${comin_m1:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN
 # directory path to data count averaging executed in model script and in
 #  bufr_avgdata.sh
 # ----------------------------------------------------------------------
-export HOMEarch=${HOMEarch:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/sdm_rtdm/${RUN})}
+export HOMEarch=${HOMEarch:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/sdm_rtdm/${NET})}
 
 #  .. AVGDarch_OUT is directory path for avg tables output by model script
 #     --------------------------------------------------------------------
 if [[ "$RUN_ENVIR" == nco ]]; then
-  export AVGDarch_IN=$HOMEarch/avgdata
   export AVGDarch_OUT=$HOMEarch/avgdata
+  mkdir -p $AVGDarch_OUT
 else
-  [ -n "$HOMEarch" ] && HOMEarch_avgdata=$HOMEarch/avgdata
-  export AVGDarch_IN=${AVGDarch_IN:-${COMIN_ROOT:?}/${obsNET}/${obsproc_ver}/sdm_rtdm/${RUN}/avgdata}
   export AVGDarch_OUT=${AVGDarch_OUT:-${COMOUT_ROOT:?}/${obsNET}/${obsproc_ver}/sdm_rtdm/${RUN}/avgdata}
   mkdir -p $AVGDarch_OUT
 fi
@@ -205,7 +223,7 @@ export PROCESS_LISTERS=${PROCESS_LISTERS:-YES}
 export MPMD=${MPMD:-"NO"}   # do not run listdumps in parallel by default
 
 # Data count average tables are generated in the 23Z run only
-if [ "$cyc" = '23' ]; then
+if [ "$cyc" = '23' -a -z "$cycM" ]; then
    export PROCESS_AVGTABLES=${PROCESS_AVGTABLES:-YES}
 else
    export PROCESS_AVGTABLES=${PROCESS_AVGTABLES:-NO}
@@ -218,7 +236,7 @@ env
 #####################
 $SCRIPTSobsproc/exdump_post.sh
 eval err_${RUN}_dump_post=$?
-eval [[ \$err_${RUN}_dump_post -ne 0 ]]  && $DATA/err_exit
+eval [[ \$err_${RUN}_dump_post -ne 0 ]] && $DATA/err_exit
 
 echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_dump_post_ran
 
@@ -228,8 +246,9 @@ echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_dump_post
  $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
 
 [ -n "$bufr_dump_ver" ]  &&  \
- echo "BUFR_DUMP version used by this job is $bufr_dump_ver" >> \
+ echo "BUFR_DUMP version used by this job is  $bufr_dump_ver" >> \
  $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
+
 
 if [ "$KEEPDATA" != YES ]; then
    cd $DATAROOT
diff --git a/jobs/JOBSPROC_URMA_PREP b/jobs/JOBSPROC_URMA_PREP
--- a/jobs/JOBSPROC_URMA_PREP
+++ b/jobs/JOBSPROC_URMA_PREP
@@ -42,8 +42,8 @@ echo
 set -x
 
 #####################################################################
-## List modules loaded for this job.
-######################################################################
+# List modules loaded for this job
+#####################################################################
 set +x
 echo
 echo "####################################################################"
@@ -59,13 +59,33 @@ set -x
 ###########################
 export obsNET=${obsNET:-obsproc}
 export NET=${NET:-urma}
-export RUN=${RUN:-urma}
 
 set +x
 echo
 echo obsNET is ${obsNET:?"###FATAL ERROR \"obsNET\" is not set"}
 echo NET is ${NET:?"###FATAL ERROR \"NET\" is not set"}
+echo
+set -x
+
+echo $job | grep "_ru_"
+err_ru=$?
+if [ $err_ru = 0 ]; then
+  export RUN=${RUN:-urma_ru}  # rapid update w/ sub-hourly cycles
+  set +x
+  echo
+  echo cycM is ${cycM:?"###FATAL ERROR \"cycM\" is not set"}
+  echo
+  set -x
+else
+  export RUN=${RUN:-urma}     # normal, hourly cycle run
+fi
+
 echo RUN is ${RUN:?"###FATAL ERROR \"RUN\" is not set"}
+
+set +x
+echo
+echo NET is ${NET}
+echo RUN is ${RUN}
 echo
 set -x
 
@@ -75,17 +95,26 @@ set -x
 export cycle=t${cyc}z
 export tmmark=tm00
 
+# Imported variable cycM, if it exists, contains cycle time minutes
+#  If cycM is imported, reset cycle in this script only (cycle_here) to 4-digit
+#   value t<HHMM>z
+#   (Note: the reset here applies only to references to $cycle, changed now to
+#          $cycle_here, in this script; downstream scripts
+#          exurma_makeprepbufr.sh.ecf and prepobs_makeprepbufr.sh will later
+#          reset actual $cycle in the same manner)
+
+cycle_here=$cycle
+[ -n "$cycM" ]  &&  cycle_here=t${cyc}${cycM}z
+
 ###############################
 # Create new working directory
 ###############################
-jobid=${jobid:-${job}.$(hostname -s).$$}
+jobid=${jobid:=${job}.$(hostname -s).$$}
 export DATA=${DATA:-$DATAROOT/${jobid}}
 rm -rf $DATA
 mkdir -p $DATA
 cd $DATA
 export pgmout=OUTPUT.$$
-
-echo dummy > sgesprep # to avoid copying unnecessary GFS file into $DATA
 
 ######################################
 # Set job log file for postmsg output
@@ -109,12 +138,10 @@ export SENDDBN=${SENDDBN:-YES}
 # Paths for obsproc items
 # -------------------------------
 export HOMEobsproc=${HOMEobsproc:\
--${PACKAGEROOT:?}/obsproc/${obsproc_ver:?\
+-${PACKAGEROOT:?}/${obsNET}/${obsproc_ver:?\
 "###FATAL ERROR \"obsproc_ver\" is not set"}}
 
-export SCRIPTSobsproc=${SCRIPTSobsproc:\
--$HOMEobsproc/scripts}
-
+export SCRIPTSobsproc=${SCRIPTSobsproc:-$HOMEobsproc/scripts}
 export USHprepobs=${USHprepobs:-$HOMEprepobs/ush}
 
 # directory path to data prep script executed in model script
@@ -132,11 +159,17 @@ export PARMPREP=${PARMPREP:-${HOMEobsproc}/parm}
 # Paths for non-obsproc items
 # ---------------------------
 
-export TANK=${TANK:-${DCOMROOT}}
 # DICTPREP is directory path to metar.tbl dictionary used in
 #  prepobs_prepacqc.sh if PREPOBS_PREPACPF is executed
 # ----------------------------------------------------------
 export DICTPREP=${DICTPREP:-${OPSROOT}/decoders/decod_shared/dictionaries_${dictionaries_ver}}
+
+# export specific urma OBSPROC variables here
+# ------------------------------------------
+export PRPC=${PRPC:-$PARMPREP/prepobs_prepdata.urma.parm}
+export CQCC=${CQCC:-$PARMPREP/prepobs_cqcbufr.urma.parm}
+export AQCC=${AQCC:-$PARMPREP/prepobs_prepacqc.urma.parm}
+export PQCC=${PQCC:-$PARMPREP/prepobs_profcqc.urma.parm}
 
 #########################################################################
 # Add some prod utilities to working directory
@@ -151,9 +184,8 @@ cp $UTILROOT/ush/setpdy.sh .; chmod +x setpdy.sh
 ##########################################
 # Run setpdy and initialize PDY variables
 ##########################################
-set +x; echo -e "\n---> path to setpdy.sh below is: `which setpdy.sh`"; set -x
-setpdy.sh
-. $DATA/PDY
+./setpdy.sh
+. PDY
 
 #########################
 # Define COM directories
@@ -163,14 +195,13 @@ export COMPONENT=${COMPONENT:-atmos}
 
 if [[ "$RUN_ENVIR" == nco ]]; then
   export COMIN=${COMIN:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
-  #export COMOUT=${COMOUT:-$(compath.py -o ${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
-  export COMOUT=${COMOUT:-$(compath.py -o  ${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
+  export COMOUT=${COMOUT:-$(compath.py -o ${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
   mkdir -m 775 -p $COMOUT
 else
   export COMIN=${COMIN:-${COMIN_ROOT:?}/${obsNET}/${obsproc_ver}/${RUN}.${PDY}}
 
 # COMOUT_ROOT for developers defaults to unique $DATA/com directory as root to
-#  prevent job from writing into a non-unique directory that might already have 
+#  prevent job from writing into a non-unique directory that might already have
 #  output in it from a previous checkout run for the same cycle
 # -----------------------------------------------------------------------------
   export COMOUT_ROOT=${COMOUT_ROOT:-${DATA}/com}
@@ -178,42 +209,48 @@ else
   mkdir -m 755 -p $COMOUT
 fi
 
-export NEMSIO_IN=${NEMSIO_IN:-.false.}        # switch for nemsio vs sigio guess
-export NETCDF_IN=${NETCDF_IN:-.true.}         # switch for netcdf history guess
-                                              # NOTE: only NESMIO_IN or NETCDF_IN can be .true.
+export NEMSIO_IN=${NEMSIO_IN:-.false.}      # switch for nemsio vs sigio guess
+export NETCDF_IN=${NETCDF_IN:-.true.}       # switch for netcdf history guess
+                                            # NOTE: only NESMIO_IN or NETCDF_IN can be .true.
 #export envir_getges=${envir_getges:-prod}
 export envir_getges=${envir_getges:-${envir:-prod}}
+export GETGES_NWG=${GETGES_NWG:-$COMROOT/nwges}
 export COMINgdas=${COMINgdas:-$(compath.py ${envir_getges}/gfs/${gfs_ver})/gdas.$PDY/${cyc}/${COMPONENT}}
 export COMINgfs=${COMINgfs:-$(compath.py ${envir_getges}/gfs/${gfs_ver})/gfs.$PDY/${cyc}/${COMPONENT}}
-if [[ "$NEMSIO_IN" == .true. || "$NETCDF_IN" == .true. ]]; then 
-  export GETGES_NWG=${GETGES_NWG:-$COMROOT/nwges} 
-  export GETGES_COM=${GETGES_COM:-$COMROOT}
-fi
 
-###########################################
+##############################################
 # SETUP URMA PREPBUFR PROCESSING VARIABLES
-###########################################
+##############################################
 
 #########################################################
 # Specify variables specific to this execution of script
 #########################################################
 
-#  Set both POE and BACK to NO in order to run this job in a serial environment
+#  Set POE *or* BACK to YES in order to run this job in a parallel environment
 
-export POE=NO
-export BACK=NO
+export POE=${POE:-NO}
+##export BACK=YES  # set BACK to YES for an alternate method of running this
+                   #  job in a parallel environment (in this case POE must be
+                   #  NO)
+
+#  NSPLIT indicates the number of parts into which the PREPDATA
+#         processing will will be split in order to run in parallel
+#         for computational efficiency (either under poe tasks when
+#         POE=YES or in background threads when BACK=YES)
+#   (Applies only when either POE=YES or BACK=YES, and PREPDATA=YES)
+#   Consider the size of the backgrounds fields if using threads.
+
+export NSPLIT=${NSPLIT:-1}
 
 #  BUFRLIST indicates the list of BUFR data dump file names to process
 
-export BUFRLIST=${BUFRLIST:-"adpsfc sfcshp msonet ascatw wdsatr satwnd"}
+export BUFRLIST=${BUFRLIST:-"adpupa proflr aircar aircft satwnd adpsfc \
+ sfcshp vadwnd goesnd msonet gpsipw rassda ascatw wdsatr"}
 
 export errPREPDATA_limit=4 # allow program PREPOBS_PREPDATA to continue at all
                            # center hour (cycle) times if foreground exit
                            # status is 4 (i.e., when either either "ADPUPA" or
                            # "ADPSFC" dump is empty)
-
-export email_GLERL="matthew.t.morris@noaa.gov"   # glerladj.sh alert recipient
-
 
 # VARIABLES THAT CONTROL PROCESSING OF INDIVIDUAL PROGRAMS
 # --------------------------------------------------------
@@ -224,45 +261,51 @@ export email_GLERL="matthew.t.morris@noaa.gov"   # glerladj.sh alert recipient
 #       if job fails in one of these programs, set offending program
 #       to NO and resubmit to "work-around" problem)
 
-export SYNDATA=NO     # NEVER execute program SYNDAT_SYNDATA
+export SYNDATA=NO                # NEVER execute program SYNDAT_SYNDATA
 
-export GLERLBUFR=YES  # Execute program PREPOBS_GLERLADJ (GLERL adjustment
-                      #  processing)
+export PREPACQC=${PREPACQC:-YES} # Execute PREPACQC script processing if YES
+   export PROCESS_ACQC=${PROCESS_ACQC:-YES} # Execute program PREPOBS_PREPACQC
+                                            #  if YES
+   export PROCESS_ACPF=${PROCESS_ACPF:-YES} # Execute program PREPOBS_PREPACPF
+                                            #  if YES
 
-export PREPACQC=NO    # NEVER execute PREPACQC script processing
-export PROCESS_ACQC=NO  # NEVER execute program PREPOBS_PREPACQC
-export PROCESS_ACPF=NO  # NEVER execute program PREPOBS_PREPACPF
+export PROFCQC=${PROFCQC:-YES}   # Execute program PREPOBS_PROFCQC  if YES
 
-export PROFCQC=NO     # NEVER execute program PREPOBS_PROFCQC
+export CQCVAD=${CQCVAD:-YES}     # Execute program PREPOBS_CQCVAD   if YES
 
-export CQCVAD=NO      # NEVER execute program PREPOBS_CQCVAD
+export CQCBUFR=${CQCBUFR:-YES}   # Execute program PREPOBS_CQCBUFR  if YES
 
-export CQCBUFR=NO     # NEVER execute program PREPOBS_CQCBUFR
+export OIQCBUFR=NO               # NEVER execute program PREPOBS_OIQCBUFR
 
-export OIQCBUFR=NO    # NEVER execute program PREPOBS_OIQCBUFR
-
-export DO_QC=NO       # NO, programs PREPOBS_PREPACQC, PREPOBS_PREPACPF,
-                      # PREPOBS_PROFCQC, PREPOBS_CQCVAD, PREPOBS_CQCBUFR and
-                      # PREPOBS_OIQCBUFR will NEVER execute regardless of
-                      # switches above
-
-export GETGUESS=${GETGUESS:-YES}
-                      # Encode first guess (background) values interpolated to
-                      # observation locations in the PREPBUFR file for use by
-                      # the q.c. programs.  This guess is always from a global
-                      # sigma guess file valid at the center PREPBUFR
-                      # processing date/time.
-                      # Defaults to "YES" in URMA runs (will only do virt.
-                      #  temp. processing here)
 
 #  -- If any of these are switched to NO it will affect the success of
 #      other programs and the success of the complete job
 #      (these are set-up only for CHECKOUT runs - they should always
 #       be set to YES for operational runs)
 
-export PREPDATA=${PREPDATA:-YES}
+export PREPDATA=${PREPDATA:-YES}  
                       # Execute programs PREPOBS_MPCOPYBUFR, PREPOBS_PREPDATA,
                       # PREPOBS_LISTHEADERS and PREPOBS_MONOPREPBUFR if YES
+
+export GETGUESS=${GETGUESS:-YES}
+                      # Encode first guess (background) values interpolated to
+                      # observation locations in the PREPBUFR file for use by
+                      # the q.c. programs.  If the center PREPBUFR processing
+                      # date/time is a multiple of 3-hrs, this guess is always
+                      # from a global sigma guess file valid at the center
+                      # PREPBUFR processing date/time.  Otherwise, this guess
+                      # is created by a linear interpolation of spectral
+                      # coefficients from global sigma guess files that span
+                      # the PREPBUFR processing date/time.  This is necessary
+                      # because global sigma guess files are valid only at
+                      # hours which are a multiple of 3.
+
+export DO_QC=${DO_QC:-YES}
+                      # IF NO, programs PREPOBS_PREPACQC, PREPOBS_PREPACPF,
+                      # PREPOBS_PROFCQC, PREPOBS_CQCVAD, PREPOBS_CQCBUFR and
+                      # PREPOBS_OIQCBUFR will NEVER execute regardless of
+                      # switches above -
+                      # should be set to NO only as a last resort!!!
 
 env
 
@@ -270,19 +313,16 @@ env
 # Execute the script
 #####################
 $SCRIPTSobsproc/exurma_makeprepbufr.sh
-eval err_${RUN}_makeprepbufr=$?
-eval [[ \$err_${RUN}_makeprepbufr -ne 0 ]] && $DATA/err_exit
+err_urma_makeprepbufr=$?
+eval err_${RUN}_prep=${err_urma_makeprepbufr}
+[[ $err_urma_makeprepbufr -ne 0 ]] && $DATA/err_exit
 
-echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_prep_ran
+echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle_here}_${RUN}_prep_ran
 
-> $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_run
+> $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_prep_run
 [ -n "$obsproc_ver" ]  &&  \
  echo "OBSPROC version is $obsproc_ver" >> \
- $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_run
-
-# Adding time lag to the end of the job to allow PREPBUFR to be copied
-#  completely before the start of the next job in the trigger's sequence
-sleep 10
+ $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_prep_run
 
 if [ "$KEEPDATA" != YES ]; then
    cd $DATAROOT
diff --git a/jobs/JOBSPROC_URMA_PREP_POST b/jobs/JOBSPROC_URMA_PREP_POST
--- a/jobs/JOBSPROC_URMA_PREP_POST
+++ b/jobs/JOBSPROC_URMA_PREP_POST
@@ -40,9 +40,10 @@ echo
 echo "####################################################################"
 echo
 set -x
+
 #####################################################################
-# List modules loaded for this job
-#####################################################################
+## List modules loaded for this job
+######################################################################
 set +x
 echo
 echo "####################################################################"
@@ -53,18 +54,36 @@ echo "####################################################################"
 echo
 set -x
 
-###########################
-# Specify NET and RUN Name
-###########################
+######################
+# Specify NET and RUN
+######################
 export obsNET=${obsNET:-obsproc}
 export NET=${NET:-urma}
-export RUN=${RUN:-urma}
 
 set +x
 echo
 echo obsNET is ${obsNET:?"###FATAL ERROR \"obsNET\" is not set"}
 echo NET is ${NET:?"###FATAL ERROR \"NET\" is not set"}
-echo RUN is ${RUN:?"###FATAL ERROR \"RUN\" is not set"}
+#echo RUN is ${RUN:?"###FATAL ERROR \"RUN\" is not set"}
+echo
+set -x
+
+echo $job | grep "_ru_"
+err_ru=$?
+if [ $err_ru = 0 ]; then
+  export RUN=${RUN:-urma_ru}  # rapid update w/ sub-hourly cycles
+  set +x
+  echo
+  echo cycM is ${cycM:?"###FATAL ERROR \"cycM\" is not set"}
+  echo
+  set -x
+else
+  export RUN=${RUN:-urma}     # normal, hourly cycle run
+fi
+set +x
+echo
+echo NET is ${NET}
+echo RUN is ${RUN}
 echo
 set -x
 
@@ -73,6 +92,17 @@ set -x
 ##############################
 export cycle=t${cyc}z
 export tmmark=tm00
+
+# Imported variable cycM, if it exists, contains cycle time minutes
+#  If cycM is imported, reset cycle in this script only (cycle_here) to 4-digit
+#   value t<HHMM>z
+#   (Note: the reset here applies only to references to $cycle, changed now to
+#          $cycle_here, in this script; downstream scripts
+#          exurma_makeprepbufr.sh.ecf and prepobs_makeprepbufr.sh will later
+#          reset actual $cycle in the same manner)
+
+cycle_here=$cycle
+[ -n "$cycM" ]  &&  cycle_here=t${cyc}${cycM}z
 
 ###############################
 # Create new working directory
@@ -106,14 +136,13 @@ export SENDDBN=${SENDDBN:-YES}
 # Paths for obsproc & prepobs items
 # ----------------------------------
 export HOMEobsproc=${HOMEobsproc:\
--${PACKAGEROOT:?}/obsproc/${obsproc_ver:?\
+-${PACKAGEROOT:?}/${obsNET}/${obsproc_ver:?\
 "###FATAL ERROR \"obsproc_ver\" is not set"}}
 
-export SCRIPTSprepobs=${SCRIPTSprepobs:\
--$HOMEprepobs/scripts}
-
+export SCRIPTSprepobs=${SCRIPTSprepobs:-$HOMEprepobs/scripts}
 export EXECobsproc=${EXECobsproc:-$HOMEobsproc/exec}
 export USHobsproc=${USHobsproc:-$HOMEobsproc/ush}
+export FIXprepobs=${FIXprepobs:-$HOMEprepobs/fix}
 
 #########################################################################
 # Add some prod utilities to working directory
@@ -128,9 +157,8 @@ cp $UTILROOT/ush/setpdy.sh .; chmod +x setpdy.sh
 ##########################################
 # Run setpdy and initialize PDY variables
 ##########################################
-set +x; echo -e "\n---> path to setpdy.sh below is: `which setpdy.sh`"; set -x
-setpdy.sh
-. $DATA/PDY
+./setpdy.sh
+. PDY
 
 #########################
 # Define COM directories
@@ -144,19 +172,18 @@ if [[ "$RUN_ENVIR" == nco ]]; then
 else
   export COMIN=${COMIN:-${COMIN_ROOT:?}/${obsNET}/${obsproc_ver}/${RUN}.${PDY}}
 
-
 # COMOUT_ROOT for developers defaults to unique $DATA/com directory as root to
-#  prevent job from writing into a non-unique directory that might already have 
-#  output in it from a previous checkout run for the same cycle 
+#  prevent job from writing into a non-unique directory that might already have
+#  output in it from a previous checkout run for the same cycle
 # -----------------------------------------------------------------------------
   export COMOUT_ROOT=${COMOUT_ROOT:-${DATA}/com}
   export COMOUT=${COMOUT:-${COMOUT_ROOT}/${obsNET}/${obsproc_ver}/${RUN}.${PDY}}
   mkdir -m 755 -p $COMOUT
 fi
 
-#########################################################
-# SETUP URMA POST-ANALYSIS PREPBUFR PROCESSING VARIABLES
-#########################################################
+##################################################
+# SETUP URMA POST-PREPBUFR PROCESSING VARIABLES
+##################################################
 
 #########################################################
 # Specify variables specific to this execution of script
@@ -171,15 +198,16 @@ env
 # Execute the script
 #####################
 $SCRIPTSprepobs/exprep_post.sh
-eval err_${RUN}_prep_post=$?
-eval [[ \$err_${RUN}_prep_post -ne 0 ]] && $DATA/err_exit
+err_prep_post=$?
+eval err_${RUN}_prep_post=${err_prep_post}
+[[ $err_prep_post -ne 0 ]] && $DATA/err_exit
 
-echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_prep_post_ran
+echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle_here}_${RUN}_prep_post_ran
 
-> $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_post_run
+> $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_prep_post_run
 [ -n "$obsproc_ver" ]  &&  \
- echo "Current OBSPROC version is $obsproc_ver" >> \
- $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_post_run
+ echo "OBSPROC version is $obsproc_ver" >> \
+ $COMOUT/obsproc_version_for_${cycle_here}_${RUN}_prep_post_run
 
 if [ "$KEEPDATA" != YES ]; then
    cd $DATAROOT
