Modified Obsproc for 'core' entry.

diff --git a/jobs/JOBSCORE_GLOBAL_DUMP_POST b/jobs/JOBSCORE_GLOBAL_DUMP_POST
--- a/jobs/JOBSCORE_GLOBAL_DUMP_POST
+++ b/jobs/JOBSCORE_GLOBAL_DUMP_POST
@@ -1,18 +1,11 @@
 #!/bin/bash
 set -xa
 date -u
-###############################################################################
-# Note: Although OBSPROC_SHARED_BUFR_DUMPLIST and OBSPROC_SHARED_BUFR_AVGDATA
-#       are linked to OBSPROC_NAM in the DUMP_POST jobs, they are not used in
-#       the catch-up cycle (tm06 through tm01) jobs.
-#           BUFR_DATACOUNT currently does not run in catch-up cycle jobs.
-#           BUFR_AVGDATA   currently does not run in catch-up cycle jobs.
-###############################################################################
 
 ###################################################################
 # Set DEBUG LEVEL - modifies info in execution trace prompt string
 ###################################################################
-export DEBUG_LEVEL=${DEBUG_LEVEL=1}
+export DEBUG_LEVEL=${DEBUG_LEVEL:-1}
 case $DEBUG_LEVEL in
   1) export PS4='+ ${SECONDS}s + ' ;;       # add seconds (this is typical case)
   0) export PS4='+ ';;                      # don't include seconds (useful if
@@ -29,10 +22,10 @@ esac
 set +x
 echo
 echo cyc is ${cyc:?"###FATAL ERROR \"cyc\" is not set"}
-echo tmmark is ${tmmark:?"###FATAL ERROR \"tmmark\" is not set"}
 echo envir is ${envir:?"###FATAL ERROR \"envir\" is not set"}
 echo job is ${job:?"###FATAL ERROR \"job\" is not set"}
 echo DATAROOT is ${DATAROOT:?"###FATAL ERROR \"DATAROOT\" is not set"}
+echo HOMEbufr_dump is ${HOMEbufr_dump:?"###FATAL ERROR \"HOMEbufr_dump\" is not set"} 
 echo
 set -x
 
@@ -40,30 +33,20 @@ set -x
 # Print out version information
 ################################
 set +x
-echo
 echo "####################################################################"
 echo
-echo "OBSPROC version is ${obsproc_ver:-not set}"
+echo "OBSCORE version is ${obscore_ver:-not set}"
 echo "BUFR_DUMP version used by this job, for dumplist, is" \
        "${bufr_dump_ver:-not set}"
+echo
 if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)bufr_dump/") -eq 0 ]];
      then echo "bufr_dump is required but not loaded! Exiting...";
      exit;
-fi
-if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)bufr_dump/") -eq 0 ]];
-	then echo "bufr_dump is required but not loaded! Exiting...";
-	exit;
 fi
 echo
 echo "####################################################################"
 echo
 set -x
-
-#####################################################################
-# List modules loaded for this job
-#####################################################################
-set +x
-echo
 echo "####################################################################"
 echo
       module list
@@ -75,9 +58,20 @@ set -x
 ######################
 # Specify NET and RUN
 ######################
-export obsNET=${obsNET:-obsproc}
-export NET=${NET:-nam}
-export RUN=${RUN:-nam}
+export obsNET=${obsNET:-obscore}
+#export NET=${NET:-gfs}
+#echo $job | grep gfs
+#err_gfs=$?
+#echo $job | grep gdas
+#err_gdas=$?
+#if [ $err_gfs = 0 ]; then
+#  export RUN=${RUN:-gfs}   # GFS
+#elif [ $err_gdas = 0 ]; then
+#  export RUN=${RUN:-gdas}  # GDAS
+#fi
+export NET=${NET:-core}
+export RUN=${RUN:-core}  # GDAS/CORE
+
 set +x
 echo
 echo obsNET is ${obsNET:?"###FATAL ERROR \"obsNET\" is not set"}
@@ -86,10 +80,11 @@ echo RUN is ${RUN:?"###FATAL ERROR \"RUN\" is not set"}
 echo
 set -x
 
-################
-# Specify cycle
-################
+##############################
+# Specify cycle and time-mark
+##############################
 export cycle=t${cyc}z
+export tmmark=tm00
 
 ###############################
 # Create new working directory
@@ -111,35 +106,32 @@ jlogfile=${jlogfile:-${DATA}/jlogfile}
 # SENDECF  - Flag Events on ECFLOW
 # SENDDBN  - Alert output file to TOC
 # SENDSDM  - Send files to SDM (via email and/or printer in bufr_datacount.sh)
-#             {on-time cycle (tm00) jobs only}
 ###############################################################################
 export SENDCOM=${SENDCOM:-YES}
 export SENDECF=${SENDECF:-YES}
 export SENDDBN=${SENDDBN:-YES}
-if [ "$tmmark" = 'tm00' ]; then
-  export SENDSDM=${SENDSDM:-YES}
-  [[ "$envir" != prod ]] && export SENDSDM=NO # parallel, don't send SDM email
-fi
+export SENDSDM=${SENDSDM:-YES}
+[[ "$envir" != prod ]] && export SENDSDM=NO  # parallel , not send email to SDM
 
 ##########################
 # Specify Execution Areas
 ##########################
 
-# -------------------------------
-# Paths for obsproc_network items
-# -------------------------------
-export HOMEobsproc=${HOMEobsproc:\
--${PACKAGEROOT:?}/${obsNET}/${obsproc_ver:?\
-"###FATAL ERROR \"obsproc_ver\" is not set"}}
+# ------------------------
+# Paths for obscore items
+# ------------------------
+export HOMEobscore=${HOMEobscore:-${PACKAGEROOT:?}/${obsNET}/${obscore_ver}:?\
+"###FATAL ERROR \"obscore_ver\" is not set"}
 
-export SCRIPTSobsproc=${SCRIPTSobsproc:-$HOMEobsproc/scripts}
-export EXECobsproc=${EXECobsproc:-$HOMEobsproc/exec}
-export USHobsproc=${USHobsproc:-$HOMEobsproc/ush}
+export SCRIPTSobscore=${SCRIPTSobscore:-$HOMEobscore/scripts}
+export EXECobscore=${EXECobscore:-$HOMEobscore/exec}
+export USHobscore=${USHobscore:-$HOMEobscore/ush}
 
-# ---------------------------------------------------------------------
+# ----------------------------------------------------------------------
 # Paths for bufr_dumplist items
 # Default variables are pre-defined when the bufr_dump module is loaded.
 # ----------------------------------------------------------------------
+
 export FIXbufr_dump=${FIXbufr_dump:-$HOMEbufr_dump/fix}
 
 #########################################################################
@@ -155,172 +147,130 @@ cp $UTILROOT/ush/setpdy.sh .; chmod +x setpdy.sh
 ##########################################
 # Run setpdy and initialize PDY variables
 ##########################################
-set +x; echo -e "\n---> path to setpdy.sh below is: `which setpdy.sh`"; set -x
-if [ -z "$PDY" ]; then
-  if test "$cyc" = "12"
-  then
-    if test "$tmmark" != "tm00"
-    then
-      # Since the 12Z catch-up cycle (tm06 through tm01) jobs run before the 12 UTC
-      # PROD_SETUP job runs we need to use the ${COMDATEROOT}/date/t00z file for our PDY
-      export cycle=t00z
-      setpdy.sh
-      . $DATA/PDY
-      export cycle=t12z
-      setpdy.sh
-      . $DATA/PDY
-    else
-      # The 12Z on-time cycle (tm00) runs after the 12 UTC PROD_SETUP job
-      setpdy.sh
-      . $DATA/PDY
-    fi
-  elif test "$cyc" = "00"
-  then
-    if test "$tmmark" != "tm00"
-    then
-      # Check to see if we are running a 00Z catch-up cycle (tm06 through tm01) job
-      # prior to run of 00 UTC PROD_SETUP - if so, update PDY by 1-day
-      setpdy.sh
-      . $DATA/PDY
-      edate=`cat ${COMDATEROOT}/date/t12z | cut -c7-14`
-      if [ $edate -eq $PDY ]
-      then
-        export PDY=`$UTILROOT/ush/finddate.sh $PDY d+1`
-        setpdy.sh
-        . $DATA/PDY
-      fi
-    else
-      # The 00Z on-time cycle (tm00) runs after the 00 UTC PROD_SETUP job
-      setpdy.sh
-      . $DATA/PDY
-    fi
-  else
-    # The 06 & 18Z jobs at all cycles after the 00 & 12 UTC PROD_SETUP jobs, resp.
-    setpdy.sh
-    . $DATA/PDY
-  fi
-else
-  # If PDY was previously specified (checkout only) fall through to here
-  setpdy.sh
-  . $DATA/PDY
-fi
+./setpdy.sh
+. PDY
 
 #########################
 # Define COM directories
 #########################
 export COMIN_ROOT=${COMIN_ROOT:-${COMROOT:-""}}
+export COMPONENT=${COMPONENT:-atmos}
 
 if [[ "$RUN_ENVIR" == nco ]]; then
-  export COMIN=${COMIN:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
-  export COMOUT=${COMOUT:-$(compath.py -o ${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
-
+  export COMIN=${COMIN:-$(compath.py ${envir}/${obsNET}/${obscore_ver}/${RUN}.${PDY}/${cyc}/${COMPONENT})}
+  export COMOUT=${COMOUT:-$(compath.py -o ${obsNET}/${obscore_ver}/${RUN}.${PDY}/${cyc}/${COMPONENT})}
   mkdir -m 775 -p $COMOUT
+# The following are used by $PROCESS_REMOREST_dm2 when it is YES
+# --------------------------------------------------------------
+  export COMINm2=${COMINm2:-$(compath.py ${envir}/${obsNET}/${obscore_ver}/${RUN}.${PDYm2}/${cyc}/${COMPONENT})}
+  export COMOUTm2=${COMOUTm2:-$(compath.py -o ${obsNET}/${obscore_ver}/${RUN}.${PDYm2}/${cyc}/${COMPONENT})}
 else
-  export COMIN=${COMIN:-${COMIN_ROOT:?}/${obsNET}/${obsproc_ver}/${RUN}.${PDY}}
+  export COMIN=${COMIN:-${COMIN_ROOT:?}/${obsNET}/${obscore_ver}/${RUN}.${PDY}/${cyc}/${COMPONENT}}
 
 # COMOUT_ROOT for developers defaults to unique $DATA/com directory as root to
 #  prevent job from writing into a non-unique directory that might already have
 #  output in it from a previous checkout run for the same cycle
 # -----------------------------------------------------------------------------
   export COMOUT_ROOT=${COMOUT_ROOT:-${DATA}/com}
-  export COMOUT=${COMOUT:-${COMOUT_ROOT:?}/${obsNET}/${obsproc_ver}/${RUN}.${PDY}}
+  export COMOUT=${COMOUT:-${COMOUT_ROOT}/${obsNET}/${obscore_ver}/${RUN}.${PDY}/${cyc}/${COMPONENT}}
   mkdir -m 755 -p $COMOUT
+# The following are used by $PROCESS_REMOREST_dm2 when it is YES
+# --------------------------------------------------------------
+  export COMINm2=${COMINm2:-${COMIN_ROOT:?}/${obsNET}/${obscore_ver}/${RUN}.${PDYm2}/${cyc}/${COMPONENT}}
+  export COMOUTm2=${COMOUTm2:-${COMOUT_ROOT}/${obsNET}/${obscore_ver}/${RUN}.${PDYm2}/${cyc}/${COMPONENT}}
+  mkdir -m 755 -p $COMOUTm2
 fi
 
-if [ "$tmmark" = 'tm00' ]; then
-
 # comin and comin_m1 are paths to dump status files for bufr_avgdata.sh
-  export comin=${comin:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
-  export comin_m1=${comin_m1:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDYm1})}
+export comin=${comin:-$(compath.py ${envir}/${obsNET}/${obscore_ver}/${RUN}.${PDY})/${cyc}/${COMPONENT}}
+export comin_m1=${comin_m1:-$(compath.py ${envir}/${obsNET}/${obscore_ver}/${RUN}.${PDYm1})/${cyc}/${COMPONENT}}
 
 # ---------------------------
-# Paths for non-obsproc items
+# Paths for non-obscore items
 # ---------------------------
 
 # directory path to data count/alert processing executed in bufr_datacount.sh
 #  and data count averaging executed in model script and in bufr_avgdata.sh
 # ---------------------------------------------------------------------------
-export HOMEarch=${HOMEarch:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/sdm_rtdm/${RUN})}
+export HOMEarch=${HOMEarch:-$(compath.py ${envir}/$obsNET/${obscore_ver})/sdm_rtdm/${NET}} 
 
 #  .. AVGDarch_IN is directory path containing 30-day avg files (read by
 #     bufr_datacount.sh)
 #     ------------------------------------------------------------------
 #  .. AVGDarch_OUT is directory path for avg tables output by model script
 #     --------------------------------------------------------------------
-  if [[ "$RUN_ENVIR" == nco ]]; then
-     export AVGDarch_IN=$HOMEarch/avgdata
-     export AVGDarch_OUT=$HOMEarch/avgdata
-  else
-    [ -n "$HOMEarch" ] && HOMEarch_avgdata=$HOMEarch/avgdata
-    export AVGDarch_IN=${AVGDarch_IN:-${COMIN_ROOT:?}/${obsNET}/${obsproc_ver}/sdm_rtdm/${RUN}/avgdata}
-    export AVGDarch_OUT=${AVGDarch_OUT:-${COMOUT_ROOT:?}/${obsNET}/${obsproc_ver}/sdm_rtdm/${RUN}/avgdata}
+if [[ "$RUN_ENVIR" == nco ]]; then
+  export AVGDarch_IN=$HOMEarch/avgdata
+  export AVGDarch_OUT=$HOMEarch/avgdata
+  if [ ! -d $AVGDarch_OUT ]; then
     mkdir -p $AVGDarch_OUT
   fi
+else
+  [ -n "$HOMEarch" ] && HOMEarch_avgdata=$HOMEarch/avgdata
+  export AVGDarch_IN=\
+${AVGDarch_IN:-${HOMEarch_avgdata:-${COMIN_ROOT:?}/${obsNET}/${obscore_ver}/sdm_rtdm/${RUN}/avgdata}}
+  export AVGDarch_OUT=${AVGDarch_OUT:-${COMOUT_ROOT:?}/${obsNET}/${obscore_ver}/sdm_rtdm/${RUN}/avgdata}
+  mkdir -p $AVGDarch_OUT
+fi
 
 #  .. OBCNTarch is directory path to write new status files to & read all status
 #     files from {can WRITE to this location only if COPY=YES (the default)}
 #     --------------------------------------------------------------------------
-  export OBCNTarch=${OBCNTarch:-$HOMEarch/obcount_30day}
+export OBCNTarch=${OBCNTarch:-$HOMEarch/obcount_30day}
 
 #  .. ALERTL is directory for alert log files output by bufr_datacount.sh
 #     -------------------------------------------------------------------
-  if [[ "$RUN_ENVIR" == nco ]]; then
-    if [[ ${envir} == prod ]]; then
-      export ALERTL=${ALERTL:-${COMROOT:?}/logs/alertlog}
-    else
-      export ALERTL=${ALERTL:-${COMROOT:?}/logs/alertlog}
-    fi
-    mkdir -p $ALERTL
-  else # developer
-    export ALERTL=${ALERTL:-${COMOUT_ROOT:?}/logs/alertlog}
-    mkdir -p $ALERTL
+if [[ "$RUN_ENVIR" == nco ]]; then
+  if [[ ${envir} == prod ]]; then
+    export ALERTL=${ALERTL:-${COMROOT:?}/logs/alertlog}
+  else
+    export ALERTL=${ALERTL:-${COMROOT:?}/logs/alertlog}
   fi
-fi  # end if [ "$tmmark" = 'tm00' ]
+  mkdir -p $ALERTL
+else # developer
+  export ALERTL=${ALERTL:-${COMOUT_ROOT:?}/logs/alertlog}
+  mkdir -p $ALERTL
+fi
 
-################################################
-# SETUP NAM DATA DUMP POST PROCESSING VARIABLES
-################################################
+########################################################
+# SETUP GDAS OR GFS DATA DUMP POST PROCESSING VARIABLES
+########################################################
 
 #########################################################
 # Specify variables specific to this execution of script
 #########################################################
-export PROCESS_REMOREST=${PROCESS_REMOREST:-YES}
-export PROCESS_UNBLKBUFR=${PROCESS_UNBLKBUFR:-NO}
-export PROCESS_LISTERS=${PROCESS_LISTERS:-YES}
+export PROCESS_DATACOUNTS=${PROCESS_DATACOUNTS:-YES} # normally runs
+export PROCESS_REMOREST=${PROCESS_REMOREST:-YES}     # normally runs
+export PROCESS_UNBLKBUFR=${PROCESS_UNBLKBUFR:-NO}    # normally does not run
+export PROCESS_LISTERS=${PROCESS_LISTERS:-YES}       # normally runs
 
-if [ "$tmmark" = 'tm00' ]; then
-  export PROCESS_DATACOUNTS=${PROCESS_DATACOUNTS:-YES}
-# Data count average tables are generated only in the 18Z on-time cycle job
-  if [ "$cyc" = '18' ]; then
-    export PROCESS_AVGTABLES=${PROCESS_AVGTABLES:-YES}
-  else
-    export PROCESS_AVGTABLES=${PROCESS_AVGTABLES:-NO}
-  fi
+# Data count average tables are generated in the 18Z run only
+if [ "$cyc" = '18' ]; then
+   export PROCESS_AVGTABLES=${PROCESS_AVGTABLES:-YES}
 else
-  export PROCESS_DATACOUNTS=NO # Not processed in catch-up cycle jobs
-  export PROCESS_AVGTABLES=NO  # Not processed in catch-up cycle jobs
+   export PROCESS_AVGTABLES=${PROCESS_AVGTABLES:-NO}
 fi
 
 env
 
+[ $RUN = gdas ] && export NET=gdas
 #####################
 # Execute the script
 #####################
-$SCRIPTSobsproc/exdump_post.sh
+$SCRIPTSobscore/exdump_post.sh
 eval err_${RUN}_dump_post=$?
 eval [[ \$err_${RUN}_dump_post -ne 0 ]] && $DATA/err_exit
 
-echo "$SITE `hostname`  --  `date -u`" > \
- $COMOUT/where_${tmmark}_${cycle}_${RUN}_dump_post_ran
+echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_dump_post_ran
 
-> $COMOUT/obsproc_version_for_${tmmark}_${cycle}_${RUN}_dump_post_run
-[ -n "$obsproc_nam_ver" ]  &&  \
- echo "OBSPROC version is $obsproc_ver" >> \
- $COMOUT/obsproc_version_for_${tmmark}_${cycle}_${RUN}_dump_post_run
+> $COMOUT/obscore_version_for_${cycle}_${RUN}_dump_post_run
+[ -n "$obscore_ver" ]  &&  \
+ echo "OBSCORE version is $obscore_ver" >> \
+ $COMOUT/obscore_version_for_${cycle}_${RUN}_dump_post_run
 
 [ -n "$bufr_dump_ver" ]  &&  \
  echo "BUFR_DUMP version used by this job is $bufr_dump_ver" >> \
- $COMOUT/obsproc_version_for_${tmmark}_${cycle}_${RUN}_dump_post_run
+ $COMOUT/obscore_version_for_${cycle}_${RUN}_dump_post_run
 
 if [ "$KEEPDATA" != YES ]; then
    cd $DATAROOT
