This PR updates Obsproc URMA codes to work on WCOSS2. (#14)
* JURMA_DUMP driver and job script files for WCOSS2, and WCOSS reference  files

* URMA job-related updates to run Obsproc on WCOSS2.

* Deleted extra files.

* Updated job script names in jobs/CMakeLists.txt file.

* Correcting some problems in jobs/JOBSPROC_URMA_DUMP
Removing obsolete JURMA_DUMP

* Updates for compath.py usage.

* Updates for compath.py usage

* Updated for compath.py usage.

* Brought scripts/exdump_post.sh into sync w/ feature/obsproc_prerelease.

* Updating scripts/exprep_post.sh to bring in synch w/
feature/obsproc_prerelease.

* Restored some logic that was over-zealously omitted.

* Removing processing after exit; triggers for SPA need to be minimal.

* Removing processing after exit; triggers for SPA need to be minimal.

* Removing processing after exit; triggers for SPA need to be minimal.

* bufr_dump module not needed for prep or prep_post processing.

* run.ver refinements.

* Bringing  ush/prepobs_makeprepbufr.sh into sync with
feature/obsproc_prerelease

Co-authored-by: Praveen Kumar <Praveen.Kumar@dlogin05.dogwood.wcoss2.ncep.noaa.gov>
Co-authored-by: Shelley Melchior <Shelley.Melchior@noaa.gov>
Co-authored-by: Shelley Melchior <53050457+ShelleyMelchior-NOAA@users.noreply.github.com>

diff --git a/jobs/JOBSPROC_URMA_DUMP_POST b/jobs/JOBSPROC_URMA_DUMP_POST
--- a/jobs/JOBSPROC_URMA_DUMP_POST
+++ b/jobs/JOBSPROC_URMA_DUMP_POST
@@ -35,21 +35,22 @@ set +x
 echo
 echo "####################################################################"
 echo
-echo "Current OBSPROC version is ${obsproc_ver:-not set}"
+echo "OBSPROC version is ${obsproc_ver:-not set}"
+echo "BUFR_DUMP version used by this job, for dumplist, is " \
+       "${bufr_dump_ver:-not set}"
+echo "grib_util module version used by this job is ${grib_util_ver:-not set}"
+if [[ $(echo $LOADEDMODULES | egrep -c "(^|:)bufr_dump/") -eq 0 ]];
+     then echo "bufr_dump is required but not loaded! Exiting...";
+     exit;
+fi
 echo
 echo "####################################################################"
 echo
 set -x
+
 #####################################################################
-# List modules loaded for this job
-#   May need to initialize the Modules package to find the module
-#   command.  Will do so for either system.
-#####################################################################
-if [ -f /usrx/local/Modules/default/init/sh ]; then  # on tide/gyre
-  . /usrx/local/Modules/default/init/sh 2>/dev/null
-elif [ -f /usrx/local/prod/modules/default/init/sh ]; then # on venus/mars
-  . /usrx/local/prod/modules/default/init/sh 2>/dev/null
-fi
+### List modules loaded for this job.
+#######################################################################
 set +x
 echo
 echo "####################################################################"
@@ -63,12 +64,15 @@ set -x
 ###########################
 # Specify NET and RUN Name
 ###########################
+export obsNET=${obsNET:-obsproc}
 export NET=${NET:-urma}
 export RUN=${RUN:-urma}
+
 set +x
 echo
-echo NET is ${NET}
-echo RUN is ${RUN}
+echo obsNET is ${obsNET:?"###FATAL ERROR \"obsNET\" is not set"}
+echo NET is ${NET:?"###FATAL ERROR \"NET\" is not set"}
+echo RUN is ${RUN:?"###FATAL ERROR \"RUN\" is not set"}
 echo
 set -x
 
@@ -93,11 +97,11 @@ export pgmout=OUTPUT.$$
 ######################################
 jlogfile=${jlogfile:-${DATA}/jlogfile}
 
-#################################################
-# SENDCOM      - Copy files to $COMOUT directory
-# SENDECF      - Flag Events on ECFLOW
-# SENDDBN      - Alert output file to TOC
-#################################################
+#############################################
+# SENDCOM  - Copy files to $COMOUT directory
+# SENDECF  - Flag Events on ECFLOW
+# SENDDBN  - Alert output file to TOC
+#############################################
 export SENDCOM=${SENDCOM:-YES}
 export SENDECF=${SENDECF:-YES}
 export SENDDBN=${SENDDBN:-YES}
@@ -110,19 +114,16 @@ export SENDDBN=${SENDDBN:-YES}
 # Paths for obsproc items
 # -------------------------------
 export HOMEobsproc=${HOMEobsproc:\
--${NWROOT:?}/obsproc.${obsproc_ver:?\
-"###FATAL ERROR \"obsproc_ver\" is not set"}}
+-${PACKAGEROOT:?}/obsproc/${obsproc_ver:?\
+"###FATAL ERROR \"obsproc_urma_ver\" is not set"}}
 
-export SCRIPTSobsproc=${SCRIPTSobsproc:\
--$HOMEobsproc/scripts}
-
+export SCRIPTSobsproc=${SCRIPTSobsproc:-$HOMEobsproc/scripts}
 export EXECobsproc=${EXECobsproc:-$HOMEobsproc/exec}
-
 export USHobsproc=${USHobsproc:-$HOMEobsproc/ush}
 
 #########################################################################
-# Add some prod utilities to working directory
-#########################################################################
+### Add some prod utilities to working directory
+###########################################################################
 echo "step ############# break ##############################" > ./break
 cp $UTILROOT/ush/err_chk   .; chmod +x err_chk
 cp $UTILROOT/ush/err_exit  .; chmod +x err_exit
@@ -144,46 +145,90 @@ export COMIN_ROOT=${COMIN_ROOT:-${COMROOT:-""}}
 
 if [[ "$RUN_ENVIR" == nco ]]; then
   export COMIN=${COMIN_ROOT:?}/obsproc/${RUN}.${PDY}
-  export COMOUT=${COMROOT:?}/obsproc/${RUN}.${PDY}
+  export COMOUT=${COMOUT:-$(compath.py ${envir}/${obsNET}/$obsproc_ver/${RUN}.${PDY})}
   mkdir -m 775 -p $COMOUT
 else
   export COMIN=${COMIN:-${COMIN_ROOT:?}/obsproc/${RUN}.${PDY}}
 
 # COMOUT_ROOT for developers defaults to unique $DATA/com directory as root to
 #  prevent job from writing into a non-unique directory that might already have 
-#  output in it from a previous checkout run for the same cycle 
+#  output in it from a previous checkout run for the same cycle
 # -----------------------------------------------------------------------------
   export COMOUT_ROOT=${COMOUT_ROOT:-${DATA}/com}
-  export COMOUT=${COMOUT:-${COMOUT_ROOT}/obsproc/${RUN}.${PDY}}
+  export COMOUT=${COMOUT:-$(compath.py ${envir}/${obsNET}/$obsproc_ver/${RUN}.${PDY})}
   mkdir -m 755 -p $COMOUT
 fi
 
-#########################################################
-# SETUP URMA POST-ANALYSIS PREPBUFR PROCESSING VARIABLES
-#########################################################
+# comin and comin_m1 are paths to dump status files for bufr_avgdata.sh
+export comin=${comin:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDY})}
+export comin_m1=${comin_m1:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/${RUN}.${PDYm1})}
+
+# ---------------------------
+# Paths for non-obsproc items
+# ---------------------------
+
+# directory path to data count averaging executed in model script and in
+#  bufr_avgdata.sh
+# ----------------------------------------------------------------------
+export HOMEarch=${HOMEarch:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/sdm_rtdm/${RUN})}
+
+#  .. AVGDarch_OUT is directory path for avg tables output by model script
+#     --------------------------------------------------------------------
+if [[ "$RUN_ENVIR" == nco ]]; then
+  export AVGDarch_IN=$HOMEarch/avgdata
+  export AVGDarch_OUT=$HOMEarch/avgdata
+else
+  [ -n "$HOMEarch" ] && HOMEarch_avgdata=$HOMEarch/avgdata
+  export AVGDarch_IN=${AVGDarch_IN:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/sdm_rtdm/${RUN}/avgdata)}
+  export AVGDarch_OUT=${AVGDarch_OUT:-$(compath.py ${envir}/${obsNET}/${obsproc_ver}/sdm_rtdm/${RUN}/avgdata)}
+  mkdir -p $AVGDarch_OUT
+fi
+
+#  .. OBCNTarch is directory path to write new status files to & read all status
+#     files from {can WRITE to this location only if COPY=YES (the default)}
+#     --------------------------------------------------------------------------
+export OBCNTarch=${OBCNTarch:-$HOMEarch/obcount_30day}
+
+#################################################
+# SETUP URMA DATA DUMP POST PROCESSING VARIABLES
+#################################################
 
 #########################################################
 # Specify variables specific to this execution of script
 #########################################################
+export PROCESS_DATACOUNTS=NO # Not processed in URMA run
 export PROCESS_REMOREST=${PROCESS_REMOREST:-YES}
-export PROCESS_TIMETWINS=NO  # can never run here
-export PROCESS_ALL_REPORT_COUNTS=NO  # can never run here
+export PROCESS_UNBLKBUFR=${PROCESS_UNBLKBUFR:-NO}
+export PROCESS_LISTERS=${PROCESS_LISTERS:-YES}
+
+export MPMD=${MPMD:-"NO"}   # do not run listdumps in parallel by default
+
+# Data count average tables are generated in the 23Z run only
+if [ "$cyc" = '23' ]; then
+   export PROCESS_AVGTABLES=${PROCESS_AVGTABLES:-YES}
+else
+   export PROCESS_AVGTABLES=${PROCESS_AVGTABLES:-NO}
+fi
 
 env
 
 #####################
 # Execute the script
 #####################
-$SCRIPTSobsproc/exprep_post.sh.ecf
-eval err_${RUN}_prep_post=$?
-eval [[ \$err_${RUN}_prep_post -ne 0 ]] && $DATA/err_exit
+$SCRIPTSobsproc/exdump_post.sh
+eval err_${RUN}_dump_post=$?
+eval [[ \$err_${RUN}_dump_post -ne 0 ]]  && $DATA/err_exit
 
-echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_prep_post_ran
+echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_dump_post_ran
 
-> $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_post_run
+> $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
 [ -n "$obsproc_ver" ]  &&  \
- echo "Current OBSPROC version is $obsproc_ver" >> \
- $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_post_run
+ echo "OBSPROC version is $obsproc_ver" >> \
+ $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
+
+[ -n "$bufr_dump_ver" ]  &&  \
+ echo "BUFR_DUMP version used by this job is $bufr_dump_ver" >> \
+ $COMOUT/obsproc_version_for_${cycle}_${RUN}_dump_post_run
 
 if [ "$KEEPDATA" != YES ]; then
    cd $DATAROOT
